name: Binary Scanner

on:
  schedule:
    - cron: '28 1 * * *'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull image
        run: |
          docker pull dopplerhq/cli:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/dopplerhq/cli:latest'
          exit-code: '1'
          ignore-unfixed: true
          scanners: vuln
